version: '3'

services:
  postgres:
    image: postgres:14.3
    container_name: cookbook-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_PASSWORD: example
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"     

volumes:
  postgres-data: